face_recognition = ['reference', 'many']
face_analyser_direction = ['left-right', 'right-left', 'top-bottom', 'bottom-top', 'small-large', 'large-small']
face_analyser_age = ['child', 'teen', 'adult', 'senior']
face_analyser_gender = ['male', 'female']
temp_frame_format = ['jpg', 'png']
output_video_encoder = ['libx264', 'libx265', 'libvpx-vp9', 'h264_nvenc', 'hevc_nvenc']
